sensors: ssc: Add missing <asm/io.h> include
  - error: implicit declaration of function '__raw_readl'
  - error: implicit declaration of function 'ioremap'

Change-Id: I460cb1647892e5f4c967f9414bc36026a723087d
Signed-off-by: Albert I <krascgq@outlook.co.id>